# Generated by Django 5.1.6 on 2025-02-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
