# Generated by Django 5.1.6 on 2025-02-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_alter_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
